#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    methods:

# Ruta configuraciones - GET | baneada

##############################################
# ------>>>> [[[JULIO NO TOCAR]]] <<<<------ #
##############################################

# USUARIOS
usuarios:
    path: /usuarios
    controller: App\Controller\UsuarioController::usuarios
    methods: GET|POST

usuario:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::usuario
    methods: GET|PUT|DELETE

# USUARIO SIGUE A USUARIO
usuario_sigue_usuarios:
    path: /usuario/{id}/seguidos
    controller: App\Controller\UsuarioController::usuariosSeguidos
    methods: GET

usuario_sigue_usuario:
    path: /usuario/{usuarioId}/sigue/{usuarioSeguidoId}
    controller: App\Controller\UsuarioController::usuarioSeguido
    methods: POST|DELETE

# CONFIGURACIONES
configuracion:
    path: /usuarios/{id}/configuracion
    controller: App\Controller\ConfiguracionController::configuracionUsuario
    methods: GET|PUT

# PODCASTS
podcasts:
    path: /podcasts
    controller: App\Controller\PodcastController::podcasts
    methods: GET

podcast:
    path: /podcast/{id}
    controller: App\Controller\PodcastController::podcast
    methods: GET

podcasts_usuario:
    path: /usuario/{id}/podcasts
    controller: App\Controller\PodcastController::podcastsUsuario
    methods: GET

seguir_podcast:
    path: /usuario/{id}/podcasts
    controller: App\Controller\PodcastController::seguirPodcast
    methods: POST|DELETE

# CAPITULOS
capitulos_podcast:
    path: /podcast/{id}/capitulos
    controller: App\Controller\CapituloController::capitulosPodcast
    methods: GET

capitulo_podcast:
    path: /podcast/{podcastId}/capitulo/{capituloId}
    controller: App\Controller\CapituloController::capituloPodcast
    methods: GET

# SUSCRIPCIONES
suscripciones_usuario:
    path: /usuario/{id}/suscripciones
    controller: App\Controller\SuscripcionController::suscripcionesUsuario
    methods: GET

suscripcion_usuario:
    path: /usuario/{usuarioId}/suscripcion/{suscripcionId}
    controller: App\Controller\SuscripcionController::suscripcionUsuario
    methods: GET

# PLAYLISTS
playlists:
    path: /playlists
    controller: App\Controller\PlaylistController::playlists
    methods: GET|POST

playlist:
    path: /playlist/{id}
    controller: App\Controller\PlaylistController::playlist
    methods: GET

playlists_usuario:
    path: /usuario/{id}/playlists
    controller: App\Controller\PlaylistController::playlistsUsuario
    methods: GET

playlist_usuario:
    path: /usuario/{usuarioId}/playlist/{playlistId}
    controller: App\Controller\PlaylistController::playlistUsuario
    methods: GET|PUT|DELETE

# CANCIONES
canciones:
    path: /canciones
    controller: App\Controller\CancionController::canciones
    methods: GET

cancion:
    path: /cancion
    controller: App\Controller\CancionController::canciones
    methods: GET

# Todavía faltan algunas

##############################################
# ------>>>> [[[JULIO NO TOCAR]]] <<<<------ #
##############################################