#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    methods:

# Ruta configuraciones - GET | baneada

# USUARIOS
usuarios:
    path: /usuarios
    controller: App\Controller\UsuarioController::usuarios
    methods: GET|POST

usuario:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::usuario
    methods: GET|PUT|DELETE

# USUARIO SIGUE A USUARIO
usuario_sigue_usuarios:
    path: /usuario/{id}/seguidos
    controller: App\Controller\UsuarioController::usuariosSeguidos
    methods: GET

usuario_sigue_usuario:
    path: /usuario/{usuarioId}/sigue/{usuarioSeguidoId}
    controller: App\Controller\UsuarioController::usuarioSeguido
    methods: POST|DELETE

# CONFIGURACIONES
configuracion:
    path: /usuarios/{usuario_id}/configuracion
    controller: App\Controller\ConfiguracionController::configuracionUsuario
    methods: GET|PUT

# PODCASTS
podcasts:
    path: /podcasts
    controller: App\Controller\PodcastController::podcasts
    methods: GET

podcast:
    path: /podcast/{id}
    controller: App\Controller\PodcastController::podcast
    methods: GET

podcasts_usuario:
    path: /usuario/{id}/podcasts
    controller: App\Controller\PodcastController::podcastsUsuario
    methods: GET

seguir_podcast:
    path: /usuario/{id}/podcasts
    controller: App\Controller\PodcastController::seguirPodcast
    methods: POST|DELETE

# CAPITULOS
capitulos_podcast:
    path: /podcast/{id}/capitulos
    controller: App\Controller\CapituloController::capitulosPodcast
    methods: GET

info_capitulo_podcast:
    path: /podcast/{id}/capitulo/{id}
    controller: App\Controller\CapituloController::infoCapituloPodcast
    methods: GET

# Se implementarán el resto de rutas por Adrián