#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#    methods:

# Ruta configuraciones - GET | baneada

# Fichero completo

# USUARIOS
usuarios:
    path: /usuarios
    controller: App\Controller\UsuarioController::usuarios
    methods: GET|POST

usuario:
    path: /usuario/{id}
    controller: App\Controller\UsuarioController::usuario
    methods: GET|PUT|DELETE

# CONFIGURACIONES
configuracion:
    path: /usuarios/{id}/configuracion
    controller: App\Controller\ConfiguracionController::configuracionUsuario
    methods: GET|PUT

# PODCASTS
podcasts:
    path: /podcasts
    controller: App\Controller\PodcastController::podcasts
    methods: GET

podcast:
    path: /podcast/{id}
    controller: App\Controller\PodcastController::podcast
    methods: GET

podcasts_usuario:
    path: /usuario/{id}/podcasts
    controller: App\Controller\PodcastController::podcastsUsuario
    methods: GET

seguir_podcast:
    path: /usuario/{id}/podcasts
    controller: App\Controller\PodcastController::seguirPodcast
    methods: POST|DELETE

# CAPITULOS
capitulos_podcast:
    path: /podcast/{id}/capitulos
    controller: App\Controller\CapituloController::capitulosPodcast
    methods: GET

capitulo_podcast:
    path: /podcast/{podcastId}/capitulo/{capituloId}
    controller: App\Controller\CapituloController::capituloPodcast
    methods: GET

# SUSCRIPCIONES
suscripciones_usuario:
    path: /usuario/{id}/suscripciones
    controller: App\Controller\SuscripcionController::suscripcionesUsuario
    methods: GET

suscripcion_usuario:
    path: /usuario/{usuarioId}/suscripcion/{suscripcionId}
    controller: App\Controller\SuscripcionController::suscripcionUsuario
    methods: GET

# PLAYLISTS
playlists:
    path: /playlists
    controller: App\Controller\PlaylistController::playlists
    methods: GET|POST

playlist:
    path: /playlist/{id}
    controller: App\Controller\PlaylistController::playlist
    methods: GET

playlists_usuario:
    path: /usuario/{id}/playlists
    controller: App\Controller\PlaylistController::playlistsUsuario
    methods: GET

playlist_usuario:
    path: /usuario/{usuarioId}/playlist/{playlistId}
    controller: App\Controller\PlaylistController::playlistUsuario
    methods: GET|PUT|DELETE

# CANCIONES
canciones:
    path: /canciones
    controller: App\Controller\CancionController::canciones
    methods: GET

cancion:
    path: /cancion
    controller: App\Controller\CancionController::canciones
    methods: GET

canciones_playlist:
    path: /playlist/{id}/canciones
    controller: App\Controller\CancionController::cancionesPlaylist
    methods: GET

cancion_playlist:
    path: /playlist/{playlistId}/cancion/{cancionId}
    controller: App\Controller\CancionController::cancionesPlaylist
    methods: POST|DELETE

# ARTISTAS
artistas:
    path: /artistas
    controller: App\Controller\ArtistaController::artistas
    methods: GET

albums_artista:
    path: /artista/{id}/albums
    controller: App\Controller\ArtistaController::albumsArtista
    methods: GET

info_album_artista:
    path: /artista/{artistaId}/album/{albumId}
    controller: App\Controller\ArtistaController::infoAlbumArtista
    methods: GET

# ALBUMS
albums:
    path: /albums
    controller: App\Controller\AlbumController::albums
    methods: GET

album:
    path: /album/{id}
    controller: App\Controller\AlbumController::album
    methods: GET

canciones_album:
    path: /album/{id}/canciones
    controller: App\Controller\AlbumController::cancionesAlbum
    methods: GET

# CALIDAD
calidades:
    path: /calidades
    controller: App\Controller\CalidadController::calidades
    methods: GET

# IDIOMA
idiomas:
    path: /idiomas
    controller: App\Controller\IdiomaController::idiomas
    methods: GET

# TIPO DESCARGA
tipos_descarga:
    path: /tipos-descarga
    controller: App\Controller\TipoDescargaController::tiposDescarga
    methods: GET